insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 4, 'Vahlen', 290, 1, 3, 2900000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Burrows', 70, 1, 2, 700000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 2, 'Parkside', 1400, 5, 20, 14000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 1, 'International', 1500, 4, 15, 15000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Meadow Vale', 170, 1, 1, 1700000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Bluejay', 80, 1, 4, 800000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Farwell', 190, 1, 4, 1900000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Fallview', 250, 1, 4, 2500000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 3, 'Blackbird', 1800, 4, 15, 18000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Artisan', 2000, 5, 10, 20000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Hanover', 100, 1, 3, 1000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 2, 'Armistice', 1700, 4, 10, 17000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 2, 'Warner', 1100, 5, 20, 11000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Barnett', 140, 1, 2, 1400000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 3, 'Kinsman', 1900, 3, 15, 19000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 1, 'High Crossing', 1000, 5, 10, 10000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 1, 'Canary', 700, 1, 5, 7000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Orin', 2000, 4, 20, 20000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Bartillon', 1900, 4, 15, 19000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Bonner', 1500, 5, 20, 15000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Walton', 160, 1, 3, 1600000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Clyde Gallagher', 70, 1, 1, 700000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Cardinal', 120, 1, 2, 1200000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 2, 'North', 1000, 2, 5, 10000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Butterfield', 300, 1, 2, 3000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 4, 'Moland', 800, 1, 5, 8000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 3, 'Talmadge', 1300, 3, 20, 13000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 2, 'Commercial', 1000, 2, 10, 10000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 3, 'Merchant', 1700, 4, 10, 17000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 3, 'Utah', 800, 1, 5, 8000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Lakewood Gardens', 1000, 4, 20, 10000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 4, '6th', 60, 1, 2, 600000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 3, 'Grover', 600, 1, 10, 6000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 1, '3rd', 800, 2, 5, 8000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 1, 'Corben', 1000, 1, 10, 10000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Duke', 120, 1, 3, 1200000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Jenifer', 300, 1, 1, 3000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 2, 'Talmadge', 220, 1, 1, 2200000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Eliot', 80, 1, 2, 800000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 1, 'Troy', 800, 1, 10, 8000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 4, 'Fulton', 500, 1, 10, 5000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 2, 'Loeprich', 600, 2, 5, 6000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Vahlen', 180, 1, 3, 1800000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Bay', 270, 1, 1, 2700000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 3, 'Park Meadow', 70, 1, 1, 700000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 4, 'Algoma', 1800, 3, 10, 18000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 1, 'Caliangt', 100, 1, 2, 1000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (3, 4, 'Anhalt', 260, 1, 2, 2600000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (2, 4, 'Menomonie', 800, 1, 5, 8000000);
insert into dich_vu (id_loai_dich_vu, id_kieu_thue, ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue) values (1, 2, 'Hanover', 1700, 4, 15, 17000000);

select * from dich_vu;