insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Golf Course', 1880, 1, 3, 1530000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Lukken', 1850, 4, 3, 3177000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Corscot', 290, 5, 7, 5721000, 4, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Oriole', 1560, 4, 11, 6072000, 2, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Springs', 1450, 5, 11, 4816000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Hooker', 1020, 4, 17, 7061000, 2, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Mifflin', 1440, 2, 15, 4633000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Acker', 810, 1, 19, 6538000, 1, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Hallows', 1590, 3, 8, 1586000, 2, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Del Mar', 740, 1, 11, 1095000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Menomonie', 1790, 5, 2, 3128000, 4, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Dexter', 1240, 5, 3, 3809000, 4, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Swallow', 1660, 3, 8, 3180000, 3, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Holmberg', 330, 4, 5, 5517000, 4, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Oriole', 500, 2, 11, 9281000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Oriole', 1980, 4, 12, 7226000, 1, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Paget', 1160, 2, 20, 5088000, 3, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Heath', 310, 4, 12, 2157000, 2, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Manitowish', 110, 5, 7, 2805000, 4, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Village', 1830, 4, 15, 4356000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Arizona', 860, 2, 9, 2148000, 4, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Huxley', 1230, 3, 18, 8934000, 4, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Schurz', 1770, 2, 2, 6668000, 4, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Lakewood', 1730, 1, 12, 3590000, 3, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Harbort', 750, 1, 17, 3353000, 4, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Melody', 1960, 2, 4, 4947000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Morningstar', 1440, 3, 19, 5860000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('3rd', 190, 5, 18, 7509000, 1, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Bultman', 1360, 1, 9, 7728000, 1, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Bay', 1840, 2, 7, 7812000, 2, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Charing Cross', 1290, 1, 10, 9599000, 3, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Mcbride', 1780, 3, 3, 9323000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Elka', 1380, 5, 9, 7951000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Little Fleur', 1400, 5, 4, 1848000, 4, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Judy', 1380, 4, 2, 1322000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Towne', 1380, 3, 4, 2732000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Columbus', 640, 4, 15, 8427000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Melvin', 730, 2, 11, 7928000, 1, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Oakridge', 1080, 2, 4, 1785000, 4, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Londonderry', 1100, 4, 7, 1457000, 1, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Springview', 1620, 5, 9, 7746000, 2, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Stang', 1780, 2, 17, 6806000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Marquette', 690, 4, 8, 6476000, 2, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Springview', 980, 4, 1, 5087000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Garrison', 60, 2, 18, 8698000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Blackbird', 910, 2, 3, 7836000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Vernon', 1200, 1, 2, 8724000, 2, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Carpenter', 250, 2, 8, 5295000, 4, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Boyd', 380, 4, 17, 7374000, 1, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Sloan', 230, 3, 4, 6336000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Sachtjen', 1030, 3, 20, 9303000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Northport', 1970, 1, 9, 2645000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Kingsford', 910, 4, 8, 4494000, 3, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Bobwhite', 1500, 5, 12, 9595000, 2, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Hoard', 1730, 2, 14, 8627000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Gateway', 1760, 1, 18, 8683000, 4, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Debra', 1820, 2, 13, 1425000, 2, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Nova', 510, 5, 6, 4686000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Havey', 940, 2, 8, 4380000, 2, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Eastlawn', 1260, 2, 18, 5906000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Monument', 1180, 3, 7, 5216000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Stuart', 1540, 4, 14, 1255000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Oak', 1440, 1, 17, 6424000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Glacier Hill', 1950, 5, 19, 7217000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Knutson', 270, 4, 15, 9429000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Thackeray', 1390, 1, 14, 1533000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Mesta', 1660, 5, 1, 5580000, 4, 3, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Bayside', 260, 1, 2, 3589000, 2, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Division', 1450, 2, 10, 2756000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Beilfuss', 1500, 4, 10, 4535000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Magdeline', 1630, 3, 17, 8580000, 4, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Westend', 570, 1, 8, 3658000, 2, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Dorton', 1380, 5, 15, 3475000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Algoma', 540, 4, 4, 8982000, 2, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Westport', 110, 1, 2, 7694000, 2, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Holy Cross', 760, 4, 1, 7084000, 1, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Blue Bill Park', 1700, 4, 19, 6869000, 4, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Morning', 1660, 1, 18, 5349000, 1, 2, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Elgar', 1870, 1, 16, 3868000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Arapahoe', 650, 1, 4, 5292000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Dexter', 970, 2, 10, 2185000, 4, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Ridgeway', 1730, 1, 20, 8727000, 1, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Sunnyside', 1120, 1, 16, 1272000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Esch', 260, 3, 8, 7052000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Katie', 250, 3, 8, 2367000, 4, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Havey', 870, 1, 19, 2379000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Sunbrook', 870, 4, 8, 8805000, 1, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Schlimgen', 630, 1, 6, 2592000, 4, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Linden', 670, 3, 8, 6779000, 4, 1, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Forest Run', 100, 3, 14, 9994000, 3, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('8th', 610, 1, 19, 2491000, 1, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Luster', 1780, 1, 16, 7216000, 4, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Arapahoe', 650, 3, 3, 7674000, 2, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Iowa', 1110, 1, 9, 6577000, 2, 2, 'Dang Trong');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Golf View', 1090, 4, 8, 4840000, 2, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Debra', 1420, 5, 8, 3597000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Vernon', 150, 2, 9, 3269000, 3, 1, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Russell', 1660, 4, 19, 6171000, 3, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Mendota', 360, 5, 11, 5568000, 1, 3, 'Da Thue');
insert into dich_vu (ten_dich_vu, dien_tich, so_tang, so_nguoi_toi_da, chi_phi_thue, id_kieu_thue, id_loai_dich_vu, trang_thai) values ('Acker', 1210, 3, 11, 9853000, 1, 2, 'Da Thue');

select * from dich_vu;